language: node_js

node_js:
  - "7"

# cache:
#   directories:
#     - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - yarn lint
  - yarn test

# for node-gyp
addons:
  apt:
    packages:
      - g++
      - build-essential
