language: node_js

node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g yarn
  - yarn

script:
  - yarn lint
  - yarn test

  # E2E test
  - yarn webdriver &
  - yarn build
  - yarn start &
  - sleep 10
  - yarn test:e2e
